
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import { ReduxProvider } from '@/lib/store/provider';
import './globals.css';
import { DirectionProvider } from './DIrectionProvider';

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '600'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body className={`${poppins.variable} font-sans h-150`}>
        <ReduxProvider>
          <DirectionProvider>
            {children}
          </DirectionProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}