import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import Header from '@/components/public/header';
import Footer from '@/components/public/footer';

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '600'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <head></head>

      <body className={`${poppins.variable} font-sans`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
